name: Ruby


# Currently ignoring everything. Change
# 'branches-ignore' to just 'branches' when ready to start 
# running tests

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: [ 2.6.x, 2.7.x, 3.x.x ]
    - name: Run the default task
      run: |
        gem install bundler -v 2.2.16
        bundle install
        bundle exec rake
